site_name: "mkdocstrings-python"
site_description: "A Python handler for mkdocstrings."
site_url: "https://mkdocstrings.github.io/python"
repo_url: "https://github.com/mkdocstrings/python"
repo_name: "mkdocstrings/python"
site_dir: "site"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, src/mkdocstrings_handlers]

nav:
- Home:
  - Overview: index.md
  - Usage: usage.md
  - Customization: customization.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
- mkdocstrings: https://mkdocstrings.github.io/

theme:
  name: material
  logo: logo.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
- admonition
- callouts:
    strip_period: no
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- coverage
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        import:
        - https://docs.python.org/3/objects.inv
        - https://mkdocstrings.github.io/objects.inv
        - https://mkdocstrings.github.io/griffe/objects.inv
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          relative_crossrefs: yes
          separate_signature: yes
          show_source: no
          show_root_full_path: no

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy
